apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels: 
    {{- range $key, $val := .Values.deploymentlabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }} 
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: {{  .Values.nginxname | repeat 5 | quote }}
        {{ if eq .Values.nginximagename "1.15.8" }}
        image: {{ .Values.nginximagename }}:{{ .Values.nginximagetag }}
        {{ else }}
        image: nginx:latest 
        {{ end }}

        ports:
        - containerPort: {{ .Values.ports.containerport }}
        volumeMounts:
        - mountPath: /etc/nginx # mount nginx-conf volumn to /etc/nginx
          readOnly: true
          name: nginx-conf
        - mountPath: /var/log/nginx
          name: log
      volumes:
      - name: nginx-conf
        configMap:
          name: {{ .Release.Name }}-configmap # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: nginx.conf
              path: nginx.conf
            - key: virtualhost.conf
              path: virtualhost/virtualhost.conf # dig directory
      - name: log
        emptyDir: {}
